server:
  port: 80

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
    file: C:/logs/spring-boot.log
    level: info

#server:
#  ssl:
#    key-store: .keystore
#    key-store-password: 123456
#    key-store-type: JKS
#    key-alias: tomcat